cask "fonts" do
  version "v0.1.1"
  sha256 "40d52270075e9370fb8701844449d4cc9b662e98c191816c65461003cbb309df"

  url "https://github.com/j5pu/fonts/archive/refs/tags/#{version}.tar.gz"
  name "Tools Fonts"
  desc "Tools Fonts"
  homepage "https://github.com/j5pu/fonts"

  font "Fonts/CARO.ttf"
  font "Fonts/Carosello-Regular.otf"
  font "Fonts/Carosello-Regular.ttf"
  font "Fonts/Chica Gogo NF W01 Regular.ttf"
  font "Fonts/Endurance W02 Bold.ttf"
  font "Fonts/Endurance W02 Regular.ttf"
  font "Fonts/Myriad-Pro-Bold_31631.ttf"
  font "Fonts/Quicksand-Bold.otf"
  font "Fonts/Quicksand-BoldItalic.otf"
  font "Fonts/Quicksand-Italic.otf"
  font "Fonts/Quicksand-Light.otf"
  font "Fonts/Quicksand-LightItalic.otf"
  font "Fonts/Quicksand-Regular.otf"
  font "Fonts/Quicksand_Dash.otf"
  # font "Fonts/Rodina-Regular.otf"
end
